# Generated by Django 5.2.4 on 2025-07-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('can_view', 'Can view documents'), ('can_create', 'Can create documents'), ('can_edit', 'Can edit documents'), ('can_delete', 'Can delete documents')],
            },
        ),
    ]
